services:
  calango-bot-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calango-bot-backend
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    env_file:
      - .env
    networks:
      - squamata-global

  calango-bot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_WS_URL=${REACT_APP_WS_URL}
        - REACT_APP_FIREBASE_BUCKET=${REACT_APP_FIREBASE_BUCKET}
        - REACT_APP_SQUAMATA_UPLOAD_API_URL=${REACT_APP_SQUAMATA_UPLOAD_API_URL}
        - REACT_APP_SQUAMATA_UPLOAD_API_KEY=${REACT_APP_SQUAMATA_UPLOAD_API_KEY}
    container_name: calango-bot-frontend
    restart: unless-stopped
    ports:
      - "3004:3000"
    env_file:
      - .env
    networks:
      - squamata-global

networks:
  squamata-global:
    external: true